//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace GestionData.Modelos
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class DefinicionesDataModel : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto DefinicionesDataModel usando la cadena de conexión encontrada en la sección 'DefinicionesDataModel' del archivo de configuración de la aplicación.
        /// </summary>
        public DefinicionesDataModel() : base("name=DefinicionesDataModel", "DefinicionesDataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DefinicionesDataModel.
        /// </summary>
        public DefinicionesDataModel(string connectionString) : base(connectionString, "DefinicionesDataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DefinicionesDataModel.
        /// </summary>
        public DefinicionesDataModel(EntityConnection connection) : base(connection, "DefinicionesDataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Clientes> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Clientes>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Clientes> _Clientes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Proveedores> Proveedores
        {
            get
            {
                if ((_Proveedores == null))
                {
                    _Proveedores = base.CreateObjectSet<Proveedores>("Proveedores");
                }
                return _Proveedores;
            }
        }
        private ObjectSet<Proveedores> _Proveedores;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Clientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToClientes(Clientes clientes)
        {
            base.AddObject("Clientes", clientes);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Proveedores. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProveedores(Proveedores proveedores)
        {
            base.AddObject("Proveedores", proveedores);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Promowork_dataModel", Name="Clientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clientes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Clientes.
        /// </summary>
        /// <param name="idCliente">Valor inicial de la propiedad IdCliente.</param>
        /// <param name="desCliente">Valor inicial de la propiedad DesCliente.</param>
        public static Clientes CreateClientes(global::System.Int32 idCliente, global::System.String desCliente)
        {
            Clientes clientes = new Clientes();
            clientes.IdCliente = idCliente;
            clientes.DesCliente = desCliente;
            return clientes;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                if (_IdCliente != value)
                {
                    OnIdClienteChanging(value);
                    ReportPropertyChanging("IdCliente");
                    _IdCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCliente");
                    OnIdClienteChanged();
                }
            }
        }
        private global::System.Int32 _IdCliente;
        partial void OnIdClienteChanging(global::System.Int32 value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdEmpresa
        {
            get
            {
                return _IdEmpresa;
            }
            set
            {
                OnIdEmpresaChanging(value);
                ReportPropertyChanging("IdEmpresa");
                _IdEmpresa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEmpresa");
                OnIdEmpresaChanged();
            }
        }
        private Nullable<global::System.Int32> _IdEmpresa;
        partial void OnIdEmpresaChanging(Nullable<global::System.Int32> value);
        partial void OnIdEmpresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumCliente
        {
            get
            {
                return _NumCliente;
            }
            set
            {
                OnNumClienteChanging(value);
                ReportPropertyChanging("NumCliente");
                _NumCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumCliente");
                OnNumClienteChanged();
            }
        }
        private Nullable<global::System.Int32> _NumCliente;
        partial void OnNumClienteChanging(Nullable<global::System.Int32> value);
        partial void OnNumClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DesCliente
        {
            get
            {
                return _DesCliente;
            }
            set
            {
                OnDesClienteChanging(value);
                ReportPropertyChanging("DesCliente");
                _DesCliente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DesCliente");
                OnDesClienteChanged();
            }
        }
        private global::System.String _DesCliente;
        partial void OnDesClienteChanging(global::System.String value);
        partial void OnDesClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DNINIFCliente
        {
            get
            {
                return _DNINIFCliente;
            }
            set
            {
                OnDNINIFClienteChanging(value);
                ReportPropertyChanging("DNINIFCliente");
                _DNINIFCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DNINIFCliente");
                OnDNINIFClienteChanged();
            }
        }
        private global::System.String _DNINIFCliente;
        partial void OnDNINIFClienteChanging(global::System.String value);
        partial void OnDNINIFClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumSSCliente
        {
            get
            {
                return _NumSSCliente;
            }
            set
            {
                OnNumSSClienteChanging(value);
                ReportPropertyChanging("NumSSCliente");
                _NumSSCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumSSCliente");
                OnNumSSClienteChanged();
            }
        }
        private global::System.String _NumSSCliente;
        partial void OnNumSSClienteChanging(global::System.String value);
        partial void OnNumSSClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DirCliente
        {
            get
            {
                return _DirCliente;
            }
            set
            {
                OnDirClienteChanging(value);
                ReportPropertyChanging("DirCliente");
                _DirCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DirCliente");
                OnDirClienteChanged();
            }
        }
        private global::System.String _DirCliente;
        partial void OnDirClienteChanging(global::System.String value);
        partial void OnDirClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdPoblacion
        {
            get
            {
                return _IdPoblacion;
            }
            set
            {
                OnIdPoblacionChanging(value);
                ReportPropertyChanging("IdPoblacion");
                _IdPoblacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPoblacion");
                OnIdPoblacionChanged();
            }
        }
        private Nullable<global::System.Int32> _IdPoblacion;
        partial void OnIdPoblacionChanging(Nullable<global::System.Int32> value);
        partial void OnIdPoblacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DirFiscalCliente
        {
            get
            {
                return _DirFiscalCliente;
            }
            set
            {
                OnDirFiscalClienteChanging(value);
                ReportPropertyChanging("DirFiscalCliente");
                _DirFiscalCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DirFiscalCliente");
                OnDirFiscalClienteChanged();
            }
        }
        private global::System.String _DirFiscalCliente;
        partial void OnDirFiscalClienteChanging(global::System.String value);
        partial void OnDirFiscalClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdPobFiscal
        {
            get
            {
                return _IdPobFiscal;
            }
            set
            {
                OnIdPobFiscalChanging(value);
                ReportPropertyChanging("IdPobFiscal");
                _IdPobFiscal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPobFiscal");
                OnIdPobFiscalChanged();
            }
        }
        private Nullable<global::System.Int32> _IdPobFiscal;
        partial void OnIdPobFiscalChanging(Nullable<global::System.Int32> value);
        partial void OnIdPobFiscalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelCliente
        {
            get
            {
                return _TelCliente;
            }
            set
            {
                OnTelClienteChanging(value);
                ReportPropertyChanging("TelCliente");
                _TelCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelCliente");
                OnTelClienteChanged();
            }
        }
        private global::System.String _TelCliente;
        partial void OnTelClienteChanging(global::System.String value);
        partial void OnTelClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FaxCliente
        {
            get
            {
                return _FaxCliente;
            }
            set
            {
                OnFaxClienteChanging(value);
                ReportPropertyChanging("FaxCliente");
                _FaxCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FaxCliente");
                OnFaxClienteChanged();
            }
        }
        private global::System.String _FaxCliente;
        partial void OnFaxClienteChanging(global::System.String value);
        partial void OnFaxClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CelCliente
        {
            get
            {
                return _CelCliente;
            }
            set
            {
                OnCelClienteChanging(value);
                ReportPropertyChanging("CelCliente");
                _CelCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CelCliente");
                OnCelClienteChanged();
            }
        }
        private global::System.String _CelCliente;
        partial void OnCelClienteChanging(global::System.String value);
        partial void OnCelClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailCliente
        {
            get
            {
                return _EmailCliente;
            }
            set
            {
                OnEmailClienteChanging(value);
                ReportPropertyChanging("EmailCliente");
                _EmailCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailCliente");
                OnEmailClienteChanged();
            }
        }
        private global::System.String _EmailCliente;
        partial void OnEmailClienteChanging(global::System.String value);
        partial void OnEmailClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WebCliente
        {
            get
            {
                return _WebCliente;
            }
            set
            {
                OnWebClienteChanging(value);
                ReportPropertyChanging("WebCliente");
                _WebCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WebCliente");
                OnWebClienteChanged();
            }
        }
        private global::System.String _WebCliente;
        partial void OnWebClienteChanging(global::System.String value);
        partial void OnWebClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomContacto
        {
            get
            {
                return _NomContacto;
            }
            set
            {
                OnNomContactoChanging(value);
                ReportPropertyChanging("NomContacto");
                _NomContacto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NomContacto");
                OnNomContactoChanged();
            }
        }
        private global::System.String _NomContacto;
        partial void OnNomContactoChanging(global::System.String value);
        partial void OnNomContactoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelContacto
        {
            get
            {
                return _TelContacto;
            }
            set
            {
                OnTelContactoChanging(value);
                ReportPropertyChanging("TelContacto");
                _TelContacto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelContacto");
                OnTelContactoChanged();
            }
        }
        private global::System.String _TelContacto;
        partial void OnTelContactoChanging(global::System.String value);
        partial void OnTelContactoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailContacto
        {
            get
            {
                return _EmailContacto;
            }
            set
            {
                OnEmailContactoChanging(value);
                ReportPropertyChanging("EmailContacto");
                _EmailContacto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailContacto");
                OnEmailContactoChanged();
            }
        }
        private global::System.String _EmailContacto;
        partial void OnEmailContactoChanging(global::System.String value);
        partial void OnEmailContactoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> CredCliente
        {
            get
            {
                return _CredCliente;
            }
            set
            {
                OnCredClienteChanging(value);
                ReportPropertyChanging("CredCliente");
                _CredCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CredCliente");
                OnCredClienteChanged();
            }
        }
        private Nullable<global::System.Byte> _CredCliente;
        partial void OnCredClienteChanging(Nullable<global::System.Byte> value);
        partial void OnCredClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdFormaPago
        {
            get
            {
                return _IdFormaPago;
            }
            set
            {
                OnIdFormaPagoChanging(value);
                ReportPropertyChanging("IdFormaPago");
                _IdFormaPago = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdFormaPago");
                OnIdFormaPagoChanged();
            }
        }
        private Nullable<global::System.Int32> _IdFormaPago;
        partial void OnIdFormaPagoChanging(Nullable<global::System.Int32> value);
        partial void OnIdFormaPagoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdCuenta
        {
            get
            {
                return _IdCuenta;
            }
            set
            {
                OnIdCuentaChanging(value);
                ReportPropertyChanging("IdCuenta");
                _IdCuenta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCuenta");
                OnIdCuentaChanged();
            }
        }
        private Nullable<global::System.Int32> _IdCuenta;
        partial void OnIdCuentaChanging(Nullable<global::System.Int32> value);
        partial void OnIdCuentaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AdjCliente
        {
            get
            {
                return _AdjCliente;
            }
            set
            {
                OnAdjClienteChanging(value);
                ReportPropertyChanging("AdjCliente");
                _AdjCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AdjCliente");
                OnAdjClienteChanged();
            }
        }
        private global::System.String _AdjCliente;
        partial void OnAdjClienteChanging(global::System.String value);
        partial void OnAdjClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ObsCliente
        {
            get
            {
                return _ObsCliente;
            }
            set
            {
                OnObsClienteChanging(value);
                ReportPropertyChanging("ObsCliente");
                _ObsCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ObsCliente");
                OnObsClienteChanged();
            }
        }
        private global::System.String _ObsCliente;
        partial void OnObsClienteChanging(global::System.String value);
        partial void OnObsClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ActivoCliente
        {
            get
            {
                return _ActivoCliente;
            }
            set
            {
                OnActivoClienteChanging(value);
                ReportPropertyChanging("ActivoCliente");
                _ActivoCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActivoCliente");
                OnActivoClienteChanged();
            }
        }
        private Nullable<global::System.Boolean> _ActivoCliente;
        partial void OnActivoClienteChanging(Nullable<global::System.Boolean> value);
        partial void OnActivoClienteChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Promowork_dataModel", Name="Proveedores")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Proveedores : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Proveedores.
        /// </summary>
        /// <param name="idProveedor">Valor inicial de la propiedad IdProveedor.</param>
        /// <param name="idEmpresa">Valor inicial de la propiedad IdEmpresa.</param>
        /// <param name="numProveedor">Valor inicial de la propiedad NumProveedor.</param>
        /// <param name="desProveedor">Valor inicial de la propiedad DesProveedor.</param>
        /// <param name="dNINIFProveedor">Valor inicial de la propiedad DNINIFProveedor.</param>
        public static Proveedores CreateProveedores(global::System.Int32 idProveedor, global::System.Int32 idEmpresa, global::System.Int32 numProveedor, global::System.String desProveedor, global::System.String dNINIFProveedor)
        {
            Proveedores proveedores = new Proveedores();
            proveedores.IdProveedor = idProveedor;
            proveedores.IdEmpresa = idEmpresa;
            proveedores.NumProveedor = numProveedor;
            proveedores.DesProveedor = desProveedor;
            proveedores.DNINIFProveedor = dNINIFProveedor;
            return proveedores;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProveedor
        {
            get
            {
                return _IdProveedor;
            }
            set
            {
                if (_IdProveedor != value)
                {
                    OnIdProveedorChanging(value);
                    ReportPropertyChanging("IdProveedor");
                    _IdProveedor = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdProveedor");
                    OnIdProveedorChanged();
                }
            }
        }
        private global::System.Int32 _IdProveedor;
        partial void OnIdProveedorChanging(global::System.Int32 value);
        partial void OnIdProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEmpresa
        {
            get
            {
                return _IdEmpresa;
            }
            set
            {
                OnIdEmpresaChanging(value);
                ReportPropertyChanging("IdEmpresa");
                _IdEmpresa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEmpresa");
                OnIdEmpresaChanged();
            }
        }
        private global::System.Int32 _IdEmpresa;
        partial void OnIdEmpresaChanging(global::System.Int32 value);
        partial void OnIdEmpresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdParticipante
        {
            get
            {
                return _IdParticipante;
            }
            set
            {
                OnIdParticipanteChanging(value);
                ReportPropertyChanging("IdParticipante");
                _IdParticipante = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdParticipante");
                OnIdParticipanteChanged();
            }
        }
        private Nullable<global::System.Int32> _IdParticipante;
        partial void OnIdParticipanteChanging(Nullable<global::System.Int32> value);
        partial void OnIdParticipanteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumProveedor
        {
            get
            {
                return _NumProveedor;
            }
            set
            {
                OnNumProveedorChanging(value);
                ReportPropertyChanging("NumProveedor");
                _NumProveedor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumProveedor");
                OnNumProveedorChanged();
            }
        }
        private global::System.Int32 _NumProveedor;
        partial void OnNumProveedorChanging(global::System.Int32 value);
        partial void OnNumProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SerieProveedor
        {
            get
            {
                return _SerieProveedor;
            }
            set
            {
                OnSerieProveedorChanging(value);
                ReportPropertyChanging("SerieProveedor");
                _SerieProveedor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SerieProveedor");
                OnSerieProveedorChanged();
            }
        }
        private global::System.String _SerieProveedor;
        partial void OnSerieProveedorChanging(global::System.String value);
        partial void OnSerieProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DesProveedor
        {
            get
            {
                return _DesProveedor;
            }
            set
            {
                OnDesProveedorChanging(value);
                ReportPropertyChanging("DesProveedor");
                _DesProveedor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DesProveedor");
                OnDesProveedorChanged();
            }
        }
        private global::System.String _DesProveedor;
        partial void OnDesProveedorChanging(global::System.String value);
        partial void OnDesProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DNINIFProveedor
        {
            get
            {
                return _DNINIFProveedor;
            }
            set
            {
                OnDNINIFProveedorChanging(value);
                ReportPropertyChanging("DNINIFProveedor");
                _DNINIFProveedor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DNINIFProveedor");
                OnDNINIFProveedorChanged();
            }
        }
        private global::System.String _DNINIFProveedor;
        partial void OnDNINIFProveedorChanging(global::System.String value);
        partial void OnDNINIFProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DirProveedor
        {
            get
            {
                return _DirProveedor;
            }
            set
            {
                OnDirProveedorChanging(value);
                ReportPropertyChanging("DirProveedor");
                _DirProveedor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DirProveedor");
                OnDirProveedorChanged();
            }
        }
        private global::System.String _DirProveedor;
        partial void OnDirProveedorChanging(global::System.String value);
        partial void OnDirProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdPoblacion
        {
            get
            {
                return _IdPoblacion;
            }
            set
            {
                OnIdPoblacionChanging(value);
                ReportPropertyChanging("IdPoblacion");
                _IdPoblacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPoblacion");
                OnIdPoblacionChanged();
            }
        }
        private Nullable<global::System.Int32> _IdPoblacion;
        partial void OnIdPoblacionChanging(Nullable<global::System.Int32> value);
        partial void OnIdPoblacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DirFiscalProveedor
        {
            get
            {
                return _DirFiscalProveedor;
            }
            set
            {
                OnDirFiscalProveedorChanging(value);
                ReportPropertyChanging("DirFiscalProveedor");
                _DirFiscalProveedor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DirFiscalProveedor");
                OnDirFiscalProveedorChanged();
            }
        }
        private global::System.String _DirFiscalProveedor;
        partial void OnDirFiscalProveedorChanging(global::System.String value);
        partial void OnDirFiscalProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdPobFiscal
        {
            get
            {
                return _IdPobFiscal;
            }
            set
            {
                OnIdPobFiscalChanging(value);
                ReportPropertyChanging("IdPobFiscal");
                _IdPobFiscal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPobFiscal");
                OnIdPobFiscalChanged();
            }
        }
        private Nullable<global::System.Int32> _IdPobFiscal;
        partial void OnIdPobFiscalChanging(Nullable<global::System.Int32> value);
        partial void OnIdPobFiscalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelProveedor
        {
            get
            {
                return _TelProveedor;
            }
            set
            {
                OnTelProveedorChanging(value);
                ReportPropertyChanging("TelProveedor");
                _TelProveedor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelProveedor");
                OnTelProveedorChanged();
            }
        }
        private global::System.String _TelProveedor;
        partial void OnTelProveedorChanging(global::System.String value);
        partial void OnTelProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FaxProveedor
        {
            get
            {
                return _FaxProveedor;
            }
            set
            {
                OnFaxProveedorChanging(value);
                ReportPropertyChanging("FaxProveedor");
                _FaxProveedor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FaxProveedor");
                OnFaxProveedorChanged();
            }
        }
        private global::System.String _FaxProveedor;
        partial void OnFaxProveedorChanging(global::System.String value);
        partial void OnFaxProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CelProveedor
        {
            get
            {
                return _CelProveedor;
            }
            set
            {
                OnCelProveedorChanging(value);
                ReportPropertyChanging("CelProveedor");
                _CelProveedor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CelProveedor");
                OnCelProveedorChanged();
            }
        }
        private global::System.String _CelProveedor;
        partial void OnCelProveedorChanging(global::System.String value);
        partial void OnCelProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailProveedor
        {
            get
            {
                return _EmailProveedor;
            }
            set
            {
                OnEmailProveedorChanging(value);
                ReportPropertyChanging("EmailProveedor");
                _EmailProveedor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailProveedor");
                OnEmailProveedorChanged();
            }
        }
        private global::System.String _EmailProveedor;
        partial void OnEmailProveedorChanging(global::System.String value);
        partial void OnEmailProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WebProveedor
        {
            get
            {
                return _WebProveedor;
            }
            set
            {
                OnWebProveedorChanging(value);
                ReportPropertyChanging("WebProveedor");
                _WebProveedor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WebProveedor");
                OnWebProveedorChanged();
            }
        }
        private global::System.String _WebProveedor;
        partial void OnWebProveedorChanging(global::System.String value);
        partial void OnWebProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomContacto
        {
            get
            {
                return _NomContacto;
            }
            set
            {
                OnNomContactoChanging(value);
                ReportPropertyChanging("NomContacto");
                _NomContacto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NomContacto");
                OnNomContactoChanged();
            }
        }
        private global::System.String _NomContacto;
        partial void OnNomContactoChanging(global::System.String value);
        partial void OnNomContactoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelContacto
        {
            get
            {
                return _TelContacto;
            }
            set
            {
                OnTelContactoChanging(value);
                ReportPropertyChanging("TelContacto");
                _TelContacto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelContacto");
                OnTelContactoChanged();
            }
        }
        private global::System.String _TelContacto;
        partial void OnTelContactoChanging(global::System.String value);
        partial void OnTelContactoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailContacto
        {
            get
            {
                return _EmailContacto;
            }
            set
            {
                OnEmailContactoChanging(value);
                ReportPropertyChanging("EmailContacto");
                _EmailContacto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailContacto");
                OnEmailContactoChanged();
            }
        }
        private global::System.String _EmailContacto;
        partial void OnEmailContactoChanging(global::System.String value);
        partial void OnEmailContactoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CredProveedor
        {
            get
            {
                return _CredProveedor;
            }
            set
            {
                OnCredProveedorChanging(value);
                ReportPropertyChanging("CredProveedor");
                _CredProveedor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CredProveedor");
                OnCredProveedorChanged();
            }
        }
        private Nullable<global::System.Int32> _CredProveedor;
        partial void OnCredProveedorChanging(Nullable<global::System.Int32> value);
        partial void OnCredProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdFormaPago
        {
            get
            {
                return _IdFormaPago;
            }
            set
            {
                OnIdFormaPagoChanging(value);
                ReportPropertyChanging("IdFormaPago");
                _IdFormaPago = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdFormaPago");
                OnIdFormaPagoChanged();
            }
        }
        private Nullable<global::System.Int32> _IdFormaPago;
        partial void OnIdFormaPagoChanging(Nullable<global::System.Int32> value);
        partial void OnIdFormaPagoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdCuenta
        {
            get
            {
                return _IdCuenta;
            }
            set
            {
                OnIdCuentaChanging(value);
                ReportPropertyChanging("IdCuenta");
                _IdCuenta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCuenta");
                OnIdCuentaChanged();
            }
        }
        private Nullable<global::System.Int32> _IdCuenta;
        partial void OnIdCuentaChanging(Nullable<global::System.Int32> value);
        partial void OnIdCuentaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ObsProveedor
        {
            get
            {
                return _ObsProveedor;
            }
            set
            {
                OnObsProveedorChanging(value);
                ReportPropertyChanging("ObsProveedor");
                _ObsProveedor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ObsProveedor");
                OnObsProveedorChanged();
            }
        }
        private global::System.String _ObsProveedor;
        partial void OnObsProveedorChanging(global::System.String value);
        partial void OnObsProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ActivoProveedor
        {
            get
            {
                return _ActivoProveedor;
            }
            set
            {
                OnActivoProveedorChanging(value);
                ReportPropertyChanging("ActivoProveedor");
                _ActivoProveedor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActivoProveedor");
                OnActivoProveedorChanged();
            }
        }
        private Nullable<global::System.Boolean> _ActivoProveedor;
        partial void OnActivoProveedorChanging(Nullable<global::System.Boolean> value);
        partial void OnActivoProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ProveedorCombustible
        {
            get
            {
                return _ProveedorCombustible;
            }
            set
            {
                OnProveedorCombustibleChanging(value);
                ReportPropertyChanging("ProveedorCombustible");
                _ProveedorCombustible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProveedorCombustible");
                OnProveedorCombustibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _ProveedorCombustible;
        partial void OnProveedorCombustibleChanging(Nullable<global::System.Boolean> value);
        partial void OnProveedorCombustibleChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdTipoProveedor
        {
            get
            {
                return _IdTipoProveedor;
            }
            set
            {
                OnIdTipoProveedorChanging(value);
                ReportPropertyChanging("IdTipoProveedor");
                _IdTipoProveedor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoProveedor");
                OnIdTipoProveedorChanged();
            }
        }
        private Nullable<global::System.Int32> _IdTipoProveedor;
        partial void OnIdTipoProveedorChanging(Nullable<global::System.Int32> value);
        partial void OnIdTipoProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Idgrupo
        {
            get
            {
                return _Idgrupo;
            }
            set
            {
                OnIdgrupoChanging(value);
                ReportPropertyChanging("Idgrupo");
                _Idgrupo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Idgrupo");
                OnIdgrupoChanged();
            }
        }
        private Nullable<global::System.Int32> _Idgrupo;
        partial void OnIdgrupoChanging(Nullable<global::System.Int32> value);
        partial void OnIdgrupoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EsGestor
        {
            get
            {
                return _EsGestor;
            }
            set
            {
                OnEsGestorChanging(value);
                ReportPropertyChanging("EsGestor");
                _EsGestor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EsGestor");
                OnEsGestorChanged();
            }
        }
        private Nullable<global::System.Boolean> _EsGestor;
        partial void OnEsGestorChanging(Nullable<global::System.Boolean> value);
        partial void OnEsGestorChanged();

        #endregion

    
    }

    #endregion

    
}
